# Generated by Django 4.2.16 on 2024-11-28 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_courses', models.CharField(max_length=45, unique=True)),
                ('theme', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('price', models.IntegerField(null=True)),
                ('level', models.CharField(max_length=45)),
                ('duration', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_message', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cours.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cours.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField()),
                ('date_payments', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cours.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cours.user')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_receiving', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cours.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cours.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserHasMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cours.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_cours.user')),
            ],
            options={
                'unique_together': {('user', 'message')},
            },
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.CheckConstraint(check=models.Q(('progress__lte', 100)), name='check_progress'),
        ),
    ]
